# archlinux
#
# VERSION       1

# use the ubuntu base image provided by dotCloud
FROM base/arch

MAINTAINER studer hello@studer.su

# make sure the package repository is up to date
RUN pacman -Syu --noconfirm
